// export const APP_WRITE_ID = 'crm-system-as-groop'
// export const DB_ID = '673f68c8001335b7e600'
// export const COLLECTION_DEALS = 'deals'
// export const COLLECTION_CUSTOMERS = 'customers'
// export const COLLECTION_COMMENTS = 'comments'
// export const STORAGE_ID = 'storage'
